version: '3.8'

services:
  # CONTAINER - MYSQL
  mysql:
    platform: linux/amd64
    image: mysql:8.0.22
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panksys_finance_db
